services:
  websearch-openapi-server:
    container_name: websearch-openapi-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}